using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using StarArk.Launcher.Models;

namespace StarArk.Launcher.Services;

public sealed class LaunchService
{
    private readonly LauncherConfig _config;
    private readonly string         _baseDir;

    public LaunchService(LauncherConfig config, string baseDir)
    {
        _config  = config;
        _baseDir = baseDir;
    }

    public bool TryLaunch(ModInfo game,
                          IEnumerable<ModInfo> addons,
                          string pipeline,
                          out string errorMessage)
    {
        errorMessage = "";
        var exe = Path.Combine(_baseDir, _config.RuntimeExecutable);
        if (!File.Exists(exe))
        {
            errorMessage = $"找不到运行时可执行文件: {exe}\n请编辑 launcher.config.json 中 RuntimeExecutable 字段。";
            return false;
        }

        // v0.3 ModSpec — engine reads enabled mods from <baseDir>/<ModsDirectory>/load_order.toml.
        // Rewrite it from the launcher's selection on every launch so the engine sees
        // exactly { game } + { selected addons }.
        var addonList = addons.ToList();
        try
        {
            WriteLoadOrder(game, addonList);
        }
        catch (System.Exception ex)
        {
            errorMessage = $"无法写入 load_order.toml: {ex.Message}";
            return false;
        }

        var args = new List<string>
        {
            $"--game={game.Id}",
            $"--pipeline={pipeline}",
        };
        foreach (var addon in addonList)
            args.Add($"--addon={addon.Id}");

        var psi = new ProcessStartInfo
        {
            FileName         = exe,
            WorkingDirectory = _baseDir,
            UseShellExecute  = false,
        };
        foreach (var a in args) psi.ArgumentList.Add(a);

        try
        {
            Process.Start(psi);
            return true;
        }
        catch (System.Exception ex)
        {
            errorMessage = ex.Message;
            return false;
        }
    }

    private void WriteLoadOrder(ModInfo game, IReadOnlyList<ModInfo> addons)
    {
        var modsDir = Path.Combine(_baseDir, _config.ModsDirectory);
        Directory.CreateDirectory(modsDir);
        var path = Path.Combine(modsDir, "load_order.toml");

        var sb = new StringBuilder();
        sb.AppendLine("# load_order.toml — auto-generated by StarArkLauncher.");
        sb.AppendLine("# Manual edits will be overwritten on next launch.");
        sb.AppendLine();
        sb.AppendLine("[[mod]]");
        sb.AppendLine($"name = \"{game.Id}\"");
        sb.AppendLine("enabled = true");
        sb.AppendLine();
        foreach (var a in addons)
        {
            sb.AppendLine("[[mod]]");
            sb.AppendLine($"name = \"{a.Id}\"");
            sb.AppendLine("enabled = true");
            sb.AppendLine();
        }
        File.WriteAllText(path, sb.ToString());
    }
}
